# Generated by Django 4.1.1 on 2022-09-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Contact',
        ),
    ]
