# Generated by Django 4.1 on 2022-09-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_signup_cname_signup_date_signup_made_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='current_status',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Exit', 'Exit')], default='Entry', max_length=10),
        ),
    ]
