# Generated by Django 4.1.1 on 2022-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_signup_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='entry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
