# Generated by Django 4.1.1 on 2022-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_signup_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='current_status',
            field=models.CharField(default='Entry', max_length=10),
        ),
    ]
